spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    master:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.26.27.54:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: 123456
#    slave:
#      type: com.alibaba.druid.pool.DruidDataSource
#      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://10.26.27.54:3306/test2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#      username: root
#      password: 123456

  # ShardingSphere 配置项
  shardingsphere:
    # 数据源配置
    datasource:
      common: #公共配置
        type: com.zaxxer.hikari.HikariDataSource # 使用 Hikari 数据库连接池
        driver-class-name: om.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      # 所有数据源的名字
      names: ds-master, ds-slave
      # 主库的数据源配置
      ds-master:
        jdbc-url: jdbc:mysql://10.26.27.54:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      # 从库数据源配置
      ds-slave:
        jdbc-url: jdbc:mysql://10.26.27.54:3306/test2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    # 读写分离配置
    rules:
      replica-query:
        data-sources:
          ds:
            primary-data-source-name: ds-master
            replica-data-source-names: ds-slave
        load-balancers:
          robin: # 必须配置，不然bean注入失败
            type: ROUND_ROBIN
            props: # 源码中默认是空，此处还必须指定一个属性
              key: none

server:
  port: 81

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.mutual.platfrom.blockchain.repository.mybatis.entity
  configuration:
    map-underscore-to-camel-case: true

